export const carsList = [
  {
    id: 1,
    type: "Легкові",
    make: "Skoda",
    model: "Octavia",
    year: 2015,
    price: 10000,
    mileage: 250000,
    fuel: "Дизель",
    engine: 1598,
    gearbox: "Автомат",
    city: "Київ",
    imgSrc:
      "https://cdn3.riastatic.com/photosnew/auto/photo/skoda_octavia__521455553f.webp",
    bodyType: "Седан",
  },
  {
    id: 2,
    type: "Легкові",
    make: "Toyota",
    model: "Camry",
    year: 2018,
    price: 15000,
    mileage: 200000,
    fuel: "Бензин",
    engine: 2000,
    gearbox: "Механіка",
    city: "Львів",
    imgSrc:
      "https://cdn1.riastatic.com/photosnew/auto/photo/toyota_camry__523982896f.webp",
    bodyType: "Седан",
  },
  {
    id: 3,
    type: "Легкові",
    make: "Honda",
    model: "Civic",
    year: 2017,
    price: 12000,
    mileage: 180000,
    fuel: "Бензин",
    engine: 1800,
    gearbox: "Автомат",
    city: "Одеса",
    imgSrc:
      "https://cdn2.riastatic.com/photosnew/auto/photo/honda_civic__523060282f.webp",
    bodyType: "Седан",
  },
  {
    id: 4,
    type: "Легкові",
    make: "Ford",
    model: "Focus",
    year: 2016,
    price: 11000,
    mileage: 150000,
    fuel: "Бензин",
    engine: 1600,
    gearbox: "Механіка",
    city: "Харків",
    imgSrc:
      "https://cdn3.riastatic.com/photosnew/auto/photo/ford_focus__494560268f.webp",
    bodyType: "Хетчбек",
  },
  {
    id: 5,
    type: "Легкові",
    make: "Chevrolet",
    model: "Cruze",
    year: 2019,
    price: 13000,
    mileage: 220000,
    fuel: "Дизель",
    engine: 2000,
    gearbox: "Автомат",
    city: "Дніпро",
    imgSrc:
      "https://cdn2.riastatic.com/photosnew/auto/photo/chevrolet_cruze__513591922f.webp",
    bodyType: "Седан",
  },
  {
    id: 6,
    type: "Легкові",
    make: "Volkswagen",
    model: "Golf",
    year: 2014,
    price: 14000,
    mileage: 170000,
    fuel: "Бензин",
    engine: 1800,
    gearbox: "Механіка",
    city: "Запоріжжя",
    imgSrc:
      "https://cdn3.riastatic.com/photosnew/auto/photo/volkswagen_golf__520304478f.webp",
    bodyType: "Хетчбек",
  },
  {
    id: 7,
    type: "Легкові",
    make: "Mazda",
    model: "3",
    year: 2017,
    price: 12500,
    mileage: 190000,
    fuel: "Дизель",
    engine: 2200,
    gearbox: "Автомат",
    city: "Кривий Ріг",
    imgSrc:
      "https://cdn0.riastatic.com/photosnew/auto/photo/mazda_3__521813045f.webp",
    bodyType: "Хетчбек",
  },
  {
    id: 8,
    type: "Легкові",
    make: "Nissan",
    model: "Sentra",
    year: 2016,
    price: 11500,
    mileage: 160000,
    fuel: "Бензин",
    engine: 1700,
    gearbox: "Механіка",
    city: "Івано-Франківськ",
    imgSrc:
      "https://cdn4.riastatic.com/photosnew/auto/photo/nissan_sentra__515499159f.webp",
    bodyType: "Седан",
  },
  {
    id: 9,
    type: "Легкові",
    make: "Hyundai",
    model: "Elantra",
    year: 2018,
    price: 13500,
    mileage: 200000,
    fuel: "Бензин",
    engine: 1900,
    gearbox: "Автомат",
    city: "Тернопіль",
    imgSrc:
      "https://cdn0.riastatic.com/photosnew/auto/photo/hyundai_elantra__524276720f.webp",
    bodyType: "Седан",
  },
  {
    id: 10,
    type: "Легкові",
    make: "Kia",
    model: "Ceed",
    year: 2015,
    price: 11000,
    mileage: 180000,
    fuel: "Дизель",
    engine: 1700,
    gearbox: "Механіка",
    city: "Рівне",
    imgSrc:
      "https://cdn.riastatic.com/photosnewr/auto/new_auto_storage/kia-ceed__2017329-620x465x72.webp",
    bodyType: "Хетчбек",
  },
  {
    id: 11,
    type: "Легкові",
    make: "Skoda",
    model: "Kodiaq",
    year: 2018,
    price: 33386,
    mileage: 62000,
    fuel: "Дизель",
    engine: 1970,
    gearbox: "Автомат",
    city: "Київ",
    imgSrc:
      "https://cdn3.riastatic.com/photosnew/auto/photo/skoda_kodiaq__508781283f.webp",
    bodyType: "Позашляховик",
  },
  {
    id: 12,
    type: "Вантажівки",
    make: "Volvo",
    model: "FH 13",
    year: 2015,
    price: 39439,
    mileage: 908000,
    fuel: "Дизель",
    engine: 12800,
    gearbox: "Автомат",
    city: "Київ",
    imgSrc:
      "https://cdn1.riastatic.com/photosnew/auto/photo/volvo_fh-13__510238276f.webp",
    bodyType: "Вантажівка",
  },
  {
    id: 12,
    type: "Вантажівки",
    make: "Scania",
    model: "R 500",
    year: 2018,
    price: 69000,
    mileage: 656000,
    fuel: "Дизель",
    engine: 13000,
    gearbox: "Автомат",
    city: "Старокостянтинів",
    imgSrc:
      "https://cdn1.riastatic.com/photosnew/auto/photo/scania_r-500__521874806f.webp",
    bodyType: "Вантажівка",
  },
];
